### PR TITLE
chore: Add code owners

### PR DESCRIPTION
**Pull request by alainncls**

### CODE REVIEW

**Review by satyajeetkolhapure — APPROVED** [review]

**Review by dawnseeker8 — APPROVED** [review]
Simple github CODEOWNERS file change.

**Review by Mrtenz — CHANGES_REQUESTED** [review]
1. There should probably be a team, instead of adding each person individually.
2. Unknown owner on line 4: make sure @satyajeetkolhapure exists and has write access to the repository
3. This means PRs can be merged without approval from `snaps-devs`. I don't think that is desirable.

**Comment by alainncls** [comment]
Closed in favour of #41

**Review by FrederikBolding — APPROVED** [review]

**Comment by FrederikBolding** [comment]
We should create a team for this and use that instead of individual people on the CODEOWNERs, but that isn't blocking.

**Comment by alainncls** [comment]
> We should create a team for this and use that instead of individual people on the CODEOWNERs, but that isn't blocking.

Yes, @kenhkan is working on it!

**Pull request merged**
